# Generated by Django 2.0.3 on 2018-05-04 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180504_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Дата публикации',
        ),
        migrations.AddField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
