# Generated by Django 2.0.3 on 2018-05-04 18:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_content',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Ваша Заявка'),
        ),
    ]
