# Generated by Django 2.0.3 on 2018-05-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20180508_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(default=1, upload_to='photo', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
