# Generated by Django 2.0.3 on 2018-05-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='', upload_to='photo', verbose_name='Фото'),
        ),
    ]
