# Generated by Django 2.0.3 on 2018-05-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20180514_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photo', verbose_name='Фото'),
        ),
    ]
