# Generated by Django 2.0.3 on 2018-05-14 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0011_auto_20180514_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('post_content', models.TextField(verbose_name='Ваша Заявка')),
                ('post_photo', models.ImageField(default='photo/default.jpg', upload_to='photo', verbose_name='Фото')),
                ('post_status', models.IntegerField(verbose_name='Статус')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Автор', to=settings.AUTH_USER_MODEL)),
                ('post_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Категория', to='post.Section')),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_section',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
