# Generated by Django 2.0.3 on 2018-05-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20180514_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(upload_to='photo', verbose_name='Фото'),
        ),
    ]
