# Generated by Django 2.0.3 on 2018-05-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(null=True, upload_to='photo', verbose_name='Фото'),
        ),
    ]
