# Generated by Django 2.0.3 on 2018-05-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20180515_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='Фото'),
        ),
    ]
