# Generated by Django 2.0.3 on 2018-05-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20180515_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(blank=True, default=1, upload_to='photo', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
