# Generated by Django 2.0.3 on 2018-05-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20180516_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_photo',
        ),
    ]
