# Generated by Django 2.0.3 on 2018-05-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_post_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_visits',
            field=models.IntegerField(default=1, verbose_name='Количество Посещений'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(blank=True, upload_to='photo', verbose_name='Фото'),
        ),
    ]
