# Generated by Django 2.0.3 on 2018-05-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20180517_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_visits',
            field=models.IntegerField(default=0, verbose_name='Количество Посещений'),
        ),
    ]
