# Generated by Django 2.0.3 on 2018-05-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, verbose_name='Город ')),
                ('country', models.CharField(max_length=30, verbose_name='Страна ')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
